name: aoc2019
version: 0.1.0.0
#synopsis:
#description:
homepage: https://github.com/githubuser/aoc2019#readme
license: BSD3
author: Author name here
maintainer: example@example.com
copyright: 2019 Author name here
category: Web
extra-source-files:
  - README.md

dependencies:
  - base >= 4.7 && < 5
  - containers
  - lens
  - time
  - extra
  - multiset
  - split
  - mtl
  - array
  - bimap
  - safe

executables:
  aoc2019:
    source-dirs: src
    main: Main.hs
