/* DO NOT EDIT: This file is automatically generated by Cabal */

/* package aoc2019-0.1.0.0 */
#ifndef VERSION_aoc2019
#define VERSION_aoc2019 "0.1.0.0"
#endif /* VERSION_aoc2019 */
#ifndef MIN_VERSION_aoc2019
#define MIN_VERSION_aoc2019(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_aoc2019 */

/* package array-0.5.3.0 */
#ifndef VERSION_array
#define VERSION_array "0.5.3.0"
#endif /* VERSION_array */
#ifndef MIN_VERSION_array
#define MIN_VERSION_array(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  5 || \
  (major1) == 0 && (major2) == 5 && (minor) <= 3)
#endif /* MIN_VERSION_array */

/* package base-4.12.0.0 */
#ifndef VERSION_base
#define VERSION_base "4.12.0.0"
#endif /* VERSION_base */
#ifndef MIN_VERSION_base
#define MIN_VERSION_base(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  12 || \
  (major1) == 4 && (major2) == 12 && (minor) <= 0)
#endif /* MIN_VERSION_base */

/* package bimap-0.4.0 */
#ifndef VERSION_bimap
#define VERSION_bimap "0.4.0"
#endif /* VERSION_bimap */
#ifndef MIN_VERSION_bimap
#define MIN_VERSION_bimap(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  4 || \
  (major1) == 0 && (major2) == 4 && (minor) <= 0)
#endif /* MIN_VERSION_bimap */

/* package containers-0.6.0.1 */
#ifndef VERSION_containers
#define VERSION_containers "0.6.0.1"
#endif /* VERSION_containers */
#ifndef MIN_VERSION_containers
#define MIN_VERSION_containers(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  6 || \
  (major1) == 0 && (major2) == 6 && (minor) <= 0)
#endif /* MIN_VERSION_containers */

/* package extra-1.6.18 */
#ifndef VERSION_extra
#define VERSION_extra "1.6.18"
#endif /* VERSION_extra */
#ifndef MIN_VERSION_extra
#define MIN_VERSION_extra(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  6 || \
  (major1) == 1 && (major2) == 6 && (minor) <= 18)
#endif /* MIN_VERSION_extra */

/* package lens-4.17.1 */
#ifndef VERSION_lens
#define VERSION_lens "4.17.1"
#endif /* VERSION_lens */
#ifndef MIN_VERSION_lens
#define MIN_VERSION_lens(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  17 || \
  (major1) == 4 && (major2) == 17 && (minor) <= 1)
#endif /* MIN_VERSION_lens */

/* package mtl-2.2.2 */
#ifndef VERSION_mtl
#define VERSION_mtl "2.2.2"
#endif /* VERSION_mtl */
#ifndef MIN_VERSION_mtl
#define MIN_VERSION_mtl(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  2 || \
  (major1) == 2 && (major2) == 2 && (minor) <= 2)
#endif /* MIN_VERSION_mtl */

/* package multiset-0.3.4.1 */
#ifndef VERSION_multiset
#define VERSION_multiset "0.3.4.1"
#endif /* VERSION_multiset */
#ifndef MIN_VERSION_multiset
#define MIN_VERSION_multiset(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  3 || \
  (major1) == 0 && (major2) == 3 && (minor) <= 4)
#endif /* MIN_VERSION_multiset */

/* package split-0.2.3.3 */
#ifndef VERSION_split
#define VERSION_split "0.2.3.3"
#endif /* VERSION_split */
#ifndef MIN_VERSION_split
#define MIN_VERSION_split(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  2 || \
  (major1) == 0 && (major2) == 2 && (minor) <= 3)
#endif /* MIN_VERSION_split */

/* package time-1.8.0.2 */
#ifndef VERSION_time
#define VERSION_time "1.8.0.2"
#endif /* VERSION_time */
#ifndef MIN_VERSION_time
#define MIN_VERSION_time(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  8 || \
  (major1) == 1 && (major2) == 8 && (minor) <= 0)
#endif /* MIN_VERSION_time */

/* tool gcc-7 */
#ifndef TOOL_VERSION_gcc
#define TOOL_VERSION_gcc "7"
#endif /* TOOL_VERSION_gcc */
#ifndef MIN_TOOL_VERSION_gcc
#define MIN_TOOL_VERSION_gcc(major1,major2,minor) (\
  (major1) <  7 || \
  (major1) == 7 && (major2) <  0 || \
  (major1) == 7 && (major2) == 0 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_gcc */

/* tool ghc-8.6.5 */
#ifndef TOOL_VERSION_ghc
#define TOOL_VERSION_ghc "8.6.5"
#endif /* TOOL_VERSION_ghc */
#ifndef MIN_TOOL_VERSION_ghc
#define MIN_TOOL_VERSION_ghc(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  6 || \
  (major1) == 8 && (major2) == 6 && (minor) <= 5)
#endif /* MIN_TOOL_VERSION_ghc */

/* tool ghc-pkg-8.6.5 */
#ifndef TOOL_VERSION_ghc_pkg
#define TOOL_VERSION_ghc_pkg "8.6.5"
#endif /* TOOL_VERSION_ghc_pkg */
#ifndef MIN_TOOL_VERSION_ghc_pkg
#define MIN_TOOL_VERSION_ghc_pkg(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  6 || \
  (major1) == 8 && (major2) == 6 && (minor) <= 5)
#endif /* MIN_TOOL_VERSION_ghc_pkg */

/* tool haddock-2.22.0 */
#ifndef TOOL_VERSION_haddock
#define TOOL_VERSION_haddock "2.22.0"
#endif /* TOOL_VERSION_haddock */
#ifndef MIN_TOOL_VERSION_haddock
#define MIN_TOOL_VERSION_haddock(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  22 || \
  (major1) == 2 && (major2) == 22 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_haddock */

/* tool hpc-0.67 */
#ifndef TOOL_VERSION_hpc
#define TOOL_VERSION_hpc "0.67"
#endif /* TOOL_VERSION_hpc */
#ifndef MIN_TOOL_VERSION_hpc
#define MIN_TOOL_VERSION_hpc(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  67 || \
  (major1) == 0 && (major2) == 67 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_hpc */

/* tool hsc2hs-0.68.5 */
#ifndef TOOL_VERSION_hsc2hs
#define TOOL_VERSION_hsc2hs "0.68.5"
#endif /* TOOL_VERSION_hsc2hs */
#ifndef MIN_TOOL_VERSION_hsc2hs
#define MIN_TOOL_VERSION_hsc2hs(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 5)
#endif /* MIN_TOOL_VERSION_hsc2hs */

/* tool pkg-config-0.29.1 */
#ifndef TOOL_VERSION_pkg_config
#define TOOL_VERSION_pkg_config "0.29.1"
#endif /* TOOL_VERSION_pkg_config */
#ifndef MIN_TOOL_VERSION_pkg_config
#define MIN_TOOL_VERSION_pkg_config(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  29 || \
  (major1) == 0 && (major2) == 29 && (minor) <= 1)
#endif /* MIN_TOOL_VERSION_pkg_config */

/* tool runghc-8.6.5 */
#ifndef TOOL_VERSION_runghc
#define TOOL_VERSION_runghc "8.6.5"
#endif /* TOOL_VERSION_runghc */
#ifndef MIN_TOOL_VERSION_runghc
#define MIN_TOOL_VERSION_runghc(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  6 || \
  (major1) == 8 && (major2) == 6 && (minor) <= 5)
#endif /* MIN_TOOL_VERSION_runghc */

/* tool strip-2.30 */
#ifndef TOOL_VERSION_strip
#define TOOL_VERSION_strip "2.30"
#endif /* TOOL_VERSION_strip */
#ifndef MIN_TOOL_VERSION_strip
#define MIN_TOOL_VERSION_strip(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  30 || \
  (major1) == 2 && (major2) == 30 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_strip */

#ifndef CURRENT_COMPONENT_ID
#define CURRENT_COMPONENT_ID "aoc2019-0.1.0.0-6eHqEx1YiiiFooNDmJjdLT-aoc2019"
#endif /* CURRENT_COMPONENT_ID */
#ifndef CURRENT_PACKAGE_VERSION
#define CURRENT_PACKAGE_VERSION "0.1.0.0"
#endif /* CURRENT_PACKAGE_VERSION */

#undef CURRENT_PACKAGE_KEY
#undef CURRENT_COMPONENT_ID
